#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 1. Run Prettier and stage any fixes
npm run prettier:fix
if [ -n "$(git diff --name-only)" ]; then
  git add .
fi

# 2. Run your linter fixes and stage them too
npm run lint:fix
if [ -n "$(git diff --name-only)" ]; then
  git add .
fi

# 3. Now exit cleanly so that Git proceeds with the original commit message
exit 0
