export enum TagsEnum {
  SIGNUP_HOME_TOP = "scg-signup--home-top",
  SIGNUP_HOME_MIDDLE = "scg-signup--home-middle",
  SIGNUP_HOME_BOTTOM = "scg-signup--home-bottom",
  SIGNUP_STRUCTURE_MIDDLE = "scg-signup--structure-middle",
  SIGNUP_STRUCTURE_TOP = "scg-signup--structure-top",
  SIGNUP_STRUCTURE_BOTTOM = "scg-signup--structure-bottom",
  SIGNUP_SHAREHOLDERS_TOP = "scg-signup--shareholders-top",
  SIGNUP_SHAREHOLDERS_MIDDLE = "scg-signup--shareholders-middle",
  SIGNUP_SHAREHOLDERS_BOTTOM = "scg-signup--shareholders-bottom",
  SIGNUP_ABOUT_TOP = "scg-signup--about-top",
  SIGNUP_ABOUT_MIDDLE = "scg-signup--about-middle",
  SIGNUP_ABOUT_BOTTOM = "scg-signup--about-bottom",
  SIGNUP_CONTACT_TOP = "scg-signup--contact-top",
  SIGNUP_CONTACT_MIDDLE = "scg-signup--contact-middle",
  SIGNUP_CONTACT_BOTTOM = "scg-signup--contact-bottom",
  SIGNUP_FAQ_TOP = "scg-signup--faq-top",
  SIGNUP_FAQ_BOTTOM = "scg-signup--faq-bottom",
  SIGNUP_FAQ_MIDDLE = "scg-signup--faq-middle",
  SIGNUP_VYARNA_PARTNERSHIP_TOP = "scg-signup--vyarna-partnership-top",
  SIGNUP_VYARNA_PARTNERSHIP_MIDDLE = "scg-signup--vyarna-partnership-middle",
  SIGNUP_VYARNA_PARTNERSHIP_BOTTOM = "scg-signup--vyarna-partnership-bottom",
}
